### ISSUE TITLE
Flattening RelPtr fields in a Rkyv Archive data struct

### ISSUE THREAD

**Issue by sffc** [djkoloski/rkyv#101]
If I have a struct using `#[derive(rkyv::Archive)]`, a new struct with "Archive" in the name is created.  This struct has the same fields as the normal struct, except that it wraps them in `RelPtr` and related types.

This is fine if your code is the one and only user of these structs.  However, what if you need to pass the structs to third-party code, like as a function argument?

I can call `.deserialize()` to get back the normal struct without the `RelPtr`s, but that defeats the purpose of Rkyv.

Since Rkyv supports trait objects, I could create a trait object to wrap my struct, and serialize the trait object.  However, then I am permanently committing to dynamic dispatch.

What I was thinking was whether there's a way to flatten the `RelPtr`s without cloning any data.  We could walk the whole data structure, flattening the `RelPtr`s to normal pointers, and return a data struct with all borrowed data and a corresponding lifetime parameter.

For example, `ArchivedString` would become `&str`, `ArchivedVec<T>` would become `&Vec<T>`, and so on.  Bonus points if this could be `Cow<str>` and `Cow<Vec<T>>`.

This wouldn't work for all possible data structs.  In particular, when we hit a complex type like `ArchivedVec<T>`, it is necessary that `T` does not contain any more fields that need to be flattened, because we want to point to the `Vec<T>` that lives in Rkyv's memory block.  I think in general, we would only support nested tuples and structs; vectors, hash maps, and so on would need to be leaves.  So it would work for fixed-size types like `i32`, but may not work with `String`.  (It would be really nice to figure out a way to have at least `String` or `&str` work in vectors.)

I could write such a conversion function manually for all my Rkyv types, but that is cumbersome, and it feels like it belongs in the core library, at least as a feature.

Thoughts?

CC @Manishearth @zbraniecki

**Comment by sffc** [comment]
The other way I was thinking to achieve this goal would be to make a trait that is used to access data, and the trait would be parameterized with multiple backends (either the normal struct or the Rkyv struct).  It's not necessary to make the trait into a trait object; it can be passed as a `&impl Trait` in function arguments.

For example,

```rust
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(rkyv::Serialize, rkyv::Archive)]
pub struct DataStruct {
    message: String,
}

trait DataStructTrait {
    fn message(&self) -> &str;
}

impl DataStructTrait for DataStruct {
    fn message(&self) -> &str {
        &self.message
    }
}

impl DataStructTrait for ArchivedDataStruct {
    fn message(&self) -> &str {
        self.message.as_str()
    }
}

fn demo(data: &impl DataStructTrait) {}
```

Can such a solution be implemented without incurring all the boilerplate?

**Comment by djkoloski** [comment]
Of the options available, I think that using a trait that abstracts over the functionality is the best. I have seen a few attempts to unify archived and unarchived types and they are typically highly complex and end up being generic anyway. I would not recommend accepting the overhead of dynamic dispatch or deserialization as a starting point.

Unfortunately, I do not think that converting archived types to their unarchived counterparts inline is possible. The reasons why are very technical, but I'll give a brief overview:

- Flattening `RelPtr`s to normal pointers isn't possible in general because pointer sizes differ between 32- and 64-bit platforms. rkyv defaults to using 32-bit relative pointers, but can switch to 64-bit ones with the `size_64` feature.
- `ArchivedString` is convertible to `&str` by dereferencing, but only because `str` is a wide pointer and we can construct it without requiring the backing data to be in a specific format. In general, this strategy works for unsized types.
- `ArchivedVec` could not be converted to `&Vec<T>` because the layout of a `Vec<T>` is (for all intents and purposes) "unknown" to external code. The layout of a `Vec<T>` may differ between platforms, so even if we could get `ArchivedVec` to fit into the same shape as a `Vec`, it might not work on all platforms.

These are many of the problems that `abomonation` faces with its serialization and deserialization.

I'm looking into providing some helpers to make it easier to implement traits for original and archived types without duplicating code, but I don't have anything solid yet. The general approach would be to just add an attribute (like `#[impl_archive]` for example) to an `impl` that would duplicate the code inside and swap the original type for the archived type.

**Comment by djkoloski** [comment]
You may also want to take a look at #100 which deals with `Cow`-like functionality. There's still some thinking to be done but there's some promise in it.

**Comment by sffc** [comment]
Thanks for the fast reply!

I guess what I was thinking in the OP was that I would create a new struct, and the new struct would have pointers into the Rkyv memory block, like Serde "partial" zero-copy deserialization.

In many ways, `RelPtr` is sugar to lazy-evaluate a pointer calculation.  When I dereference a `RelPtr`, conversions like 32/64-bit need to take place.  So essentially, my suggestion would be to cache the results of those operations in a new struct.  The new struct would just contain a bunch of pre-computed absolute pointers into the Rkyv memory block.

> Of the options available, I think that using a trait that abstracts over the functionality is the best.

Are there any plans to auto-generate these traits, or is that something left up to the client?

**Comment by djkoloski** [comment]
I think that’s an interesting idea, though I think you’d end up making many structs with those cached results in it. It’s a use case I think I’d need some hard numbers on before I could decide what sort of shape it would take.

As for auto-generation, that could be left to the client but I think another crate would be a good way to fill that feature gap. If it’s a common enough pattern, it might be worth just integrating into rkyv proper though.

**Comment by sffc** [comment]
> I think that’s an interesting idea, though I think you’d end up making many structs with those cached results in it.

You would need only one stack-allocated struct to hold all the pointers, so long as the "leaf" fields conform to certain invariants that I put in the OP.  No heap allocations would be required at all; I think it would be `no_std`-compatible.

The invariants would likely prevent `Vec<String>`, which is sad.  But we could probably cook up a workaround for that specific case.

**Comment by djkoloski** [comment]
Under those conditions, you could build on top of rkyv to get this kind of functionality:

```rust
pub struct DataStruct {
    message: String,
}

pub struct RefDataStruct<'a> {
    message: &'a str,
}

impl<'a> From<&'a Archived<DataStruct>> for RefDataStruct<'a> {
    fn from(value: &'a Archived<DataStruct>) -> Self {
        RefDataStruct{
            message: value.as_ref(),
        }
    }
}
```

This seems like something you could derive with a pretty simple proc-macro, something like:

```rust
pub struct DataStruct {
    message: String,
    points: Vec<(f32, f32, f32)>,
}

// This would be a new proc-macro
#[derive(FromRef)]
// and this would tell it what to write the From implementation with
#[from_ref = "Archived<DataStruct>"]
pub struct RefDataStruct<'a> {
    message: &'a str,
    points: &'a [(f32, f32, f32)],
}
```

The idea here is that rkyv can implement partial zero-copy deserialization as an extension of total zero-copy deserialization. You could even pick and choose how to handle cases like `Vec<String>` as mentioned above (either `Vec<&'a str>` or `&'a [ArchivedString]` would be easy).

**Comment by djkoloski** [comment]
Closing this, feel free to reopen if the solution above doesn't work for you
