### ISSUE TITLE
Improve performance of check_archived_root

### ISSUE THREAD

**Issue by sffc** [djkoloski/rkyv#105]
I made two little example files:

```rust
#![no_main]

use iai::black_box;
use rkyv::{check_archived_root, Aligned};

const RKYV_BUF: Aligned<[u8; 88]> = Aligned([
    0, 1, 2, 0, 4, 5, 6, 0, 8, 9, 10, 0, 12, 13, 14, 0, 16, 17, 18, 0, 20, 21, 22, 0, 24, 25, 26,
    0, 28, 29, 30, 0, 32, 33, 34, 0, 36, 37, 38, 0, 40, 41, 42, 0, 44, 45, 46, 0, 48, 49, 50, 0,
    52, 53, 54, 0, 56, 57, 58, 0, 60, 61, 62, 0, 64, 65, 66, 0, 68, 69, 70, 0, 72, 73, 74, 0, 76,
    77, 78, 0, 176, 255, 255, 255, 20, 0, 0, 0,
]);

#[no_mangle]
fn main(_argc: isize, _argv: *const *const u8) -> isize {
    let archived = check_archived_root::<Vec<u32>>(black_box(&RKYV_BUF.0)).unwrap();
    assert_eq!(52629240u32, archived.iter().copied().sum());
    0
}
```

The second is the same, except that I use `archived_root` instead of `check_archived_root`.

The unchecked version compiles to a nice and compact 475 bytes (measured using the wasm32-unknown-unknown target) and requires only 96 instructions, according to iai.  However, the checked version compiles to 10078 bytes and requires 4858 instructions.

Much of the code size is `dlmalloc`.  If the checking code requires `dlmalloc`, then it's not `#[no_std]` compatible.  I don't understand why validation code needs to allocate memory; it should just do some basic checks on the data and return "valid" or "not valid".

Suggestions for improvement:

1. Make `check_archived_root` be `#[no_std]`
2. Follows from (1): verify that code size and performance hit are minimal when using `check_archived_root` instead of `unsafe { archived_root }`.

**Comment by djkoloski** [comment]
`no_std` will be possible after https://github.com/djkoloski/bytecheck/issues/3 is fixed.

**Comment by djkoloski** [comment]
For some extra context, checking an archive requires `dlmalloc` in most cases because the validation context usually needs to check that no objects pointed to (via `RelPtr`) overlap in memory since that could lead to vulnerabilities with mutable access and recursive attacks. If your use case does require `RelPtr`s but you're not worried about these kinds of attacks, you can provide a validation context that skips the checks. Another possible alternative is to make a `no_std` compliant validator that has a fixed size array and errors out if too many memory regions are used.

**Comment by sffc** [comment]
Thanks for the reply!  Some ideas...

1. If the `RelPtr`s always point in the same direction (always forwards or always backwards), then recursive pointers can't exist.  Is there a way to enforce such a constraint on rkyv archives?
2. Can you use a O(1) space cycle detection algorithm like tortoise-and-hare?

**Comment by djkoloski** [comment]
> If the `RelPtrs` always point in the same direction (always forwards or always backwards), then recursive pointers can't exist. Is there a way to enforce such a constraint on rkyv archives?

This was originally the design for `RelPtrs`, but I relaxed it to allow for forward or backwards pointers to allow users to make e.g. archived graphs and allow for archives with the root at the front. This would prevent infinite loop attacks (since validation must _eventually_ terminate), but not shared memory attacks (two objects expect to own some memory that both point to).

> Can you use a O(1) space cycle detection algorithm like tortoise-and-hare?

Cycle detection is good, but only half of the problem. Ownership constraint violation also needs to be detected, which will always require more than O(1) space.

Memory ownership constraints are important for mutable archives, since the compiler may optimize memory accesses assuming that some const values won't change. If aliasing occurs, the values must not be mutable. This can be enforced with wrapper types like interning to make shared memory safe, but by default aliased values must not be mutable.

**Comment by djkoloski** [comment]
Closing in favor of #107. Feel free to reopen or open a new issue if appropriate.
