### ISSUE TITLE
Compatibility with compression and streaming deserialization

### ISSUE THREAD

**Issue by aldanor** [djkoloski/rkyv#48]
This question may have an obvious answer, but it's not so obvious from the docs: how would this crate play with compression?

The use case is this - I have a few million objects in a file (let's say they are of the same type) that I need to load fast in a streaming fashion (i.e., deserialize, process, throw it away), so if I have a [`zstd::Decoder`](https://docs.rs/zstd/0.6.0+zstd.1.4.8/zstd/stream/read/struct.Decoder.html) that implements `BufRead` and can provide a decompressed stream of bytes, how would `rkyv` play with it?

(It's also not very clear from the docs if `rkyv` is a suitable choice for streaming zero-copy deserialization tasks in general)

Thanks!

**Comment by djkoloski** [comment]
This sort of thing is definitely possible, if a bit clunky at the moment. You'll need to archive each object separately and record some metadata about where its archive begins and ends. Because decompressors are typically streaming, I would suggest a basic object header that contains the length of the archive and the position of the root object.

The compression process will probably look something like:

```rust
let mut compressor = zstd::Encoder::new(file, level);

// Write the total number of objects
compressor.write((objects.len() as u32).to_ne_bytes())?;
for object in objects {
    let mut writer = ArchiveWriter::new(Vec::new());
    let pos = writer.archive(object)?;
    let buf = writer.into_inner();

    // Write the length of the object
    compressor.write((buf.len() as u32).to_ne_bytes())?;
    // Write the position of the root
    compressor.write((pos as u32).to_ne_bytes())?;
    /// Write the archive
    compressor.write(buf.as_slice())?;
}
```

and the decompression process will probably look something like:

```rust
fn read_u32<R: Read>(reader: R) -> Result<u32, Error> {
    let bytes = [0; 4];
    reader.read_exact(bytes.as_mut_slice())?;
    u32::from_ne_bytes(bytes)
}

let mut decompressor = zstd::Decoder::new(file);

// Read the total number of objects
let count = read_u32(&mut decompressor)? as usize;
for i in 0..count {
    // Read the length of the archive
    let len = read_u32(&mut decompressor)? as usize;
    // Read the position of the root
    let pos = read_u32(&mut decompressor)? as usize;

    let archive = vec![Aligned(0); len];
    // Read the archive
    decompressor.read_exact(archive.as_mut_slice())?;

    // Get the root object
    let object = unsafe { archived_value::<Object>(archive.as_slice(), pos) };
    process_object(object);
}
```

You might be able to save a few bytes by using [Seek](https://docs.rs/rkyv/0.3.0/rkyv/trait.Seek.html) and `archive_root`, but I don't think Seek is supported for vectors yet.

**Comment by aldanor** [comment]
Thanks for clarifying! I will try to implement something like this and then maybe report back if there's any issues along the way.

(Closing this since it was more of a question rather than an issue.)
