### ISSUE TITLE
Struct with trait object

### ISSUE THREAD

**Issue by dennybritz** [djkoloski/rkyv#62]
I'm currently using serde + typetag for this and I'm wondering if it's possible to do something similar with `rkyv`:

```rust
#[archive_dyn]
trait TestTrait {}

#[derive(Archive)]
#[archive(derive(TypeName))]
struct TestStruct {
    inner: Box<dyn TestTrait>
}
```

**Comment by djkoloski** [comment]
Yes, you can see an example in the [documentation for ArchiveDyn](https://docs.rs/rkyv_dyn/0.3.1/rkyv_dyn/trait.ArchiveDyn.html).

**Comment by dennybritz** [comment]
Sorry, but could you point me to the example? I can't seem to find it  in the documentation. Since the above doesn't compile I'm assuming you need to manually derive `Archive` to make it work? Is there an example of how you do that with such a boxed trait object member?

**Comment by djkoloski** [comment]
Here's a fully worked example:

```rust
use rkyv::{Archive, ArchiveWriter, Write};
use rkyv_dyn::archive_dyn;
use rkyv_typename::TypeName;

#[archive_dyn]
trait TestTrait {
    fn log(&self);
}

#[derive(Archive)]
#[archive(derive(TypeName))]
struct TestStruct {
    inner: Box<dyn ArchiveTestTrait>,
}

#[archive_dyn]
impl TestTrait for i32 {
    fn log(&self) {
        println!("{}", *self)
    }
}

fn main() {
    let test = TestStruct {
        inner: Box::new(42) as Box<dyn ArchiveTestTrait>,
    };

    let mut writer = ArchiveWriter::new(Vec::new());
    let pos = writer.archive(&test).expect("failed to archive");
    let buf = writer.into_inner();

    let archived_test = unsafe { rkyv::archived_value::<TestStruct>(buf.as_ref(), pos) };
    archived_test.inner.log();
}
```

I think the error you were getting should have been something like: `the trait bound (dyn TestTrait + 'static): Archive is not satisfied`. This is because `TestTrait` does not have `Archive` as a supertrait.

This is a little bit confusing and probably deserves being called out explicitly in the book, but you don't directly archive your trait. Instead, you archive a new trait that's generated by the `#[archive_dyn]` macro (named Archive + your trait name by default, but you can configure it). This new trait shim is empty and has your trait and `ArchiveRef` as supertraits. This is an alternative to directly adding `ArchiveRef` as a supertrait to your trait.

rkyv prefers the trait shim approach so that you can implement your trait on types that you may not also want (or be able) to implement `Archive` on.

I'll put a page or so about `rkyv_dyn` in the book for the next release.

**Comment by dennybritz** [comment]
Thanks for the explanation, that makes sense and your example works!

One side effect of this shim approach is that other macros (or extension trait) on the original type don't apply to the shim. For example, I was also deriving `#[typetag::serde(tag = "type")]` on the original trait, but of course that wouldn't be applied to the generated `ArchiveTestTrait` trait - it's probably not a big deal in my case since I'd be replacing serde with rkyv, but there may be cases where this makes things difficult.

**Comment by djkoloski** [comment]
That's a good point, I'll think about that some more. Maybe an attribute like `#[archive_dyn(no_shim)]` could be possible. It would be a bit of work though, so unless it becomes a more widely-requested feature I'll probably leave it on the backburner.

There is also an example of doing everything by hand with no macros in the test crate. You may be able to use the macro for the impls but not for the trait to get the same result.
