### ISSUE TITLE
Serialized size

### ISSUE THREAD

**Issue by mountainfloating** [djkoloski/rkyv#77]
I was looking for a way to calculate the serialized size without actually serializing it. Is there currently a function that does it and I was just overlooking it? If not something like std::mem::size_of_val would be nice.
I would need this to length-encode a struct without actually allocating it first.

**Comment by djkoloski** [comment]
You might be able to do this with a dummy serializer that doesn’t write any bytes and just updates its position and tracks how many bytes have been written. A generic mem::size_of_val wouldn’t quite work because it would miss alignment padding and wouldn’t properly calculate the size of, for example shared pointers.

The downside here is that you’d have to serialize twice. Depending on your use case, you might be able to use serialize_root with a seekable writer.

**Comment by djkoloski** [comment]
Got some time to put an example together, this should do what you want:

```rust
use rkyv::{Fallible, ser::Serializer};

pub struct MockSerializer {
    pos: usize,
}

impl MockSerializer {
    pub fn new() -> Self {
        Self { pos: 0 }
    }
}

impl Fallible for MockSerializer {
    type Error = ();
}

impl Serializer for MockSerializer {
    fn pos(&self) -> usize {
        self.pos
    }

    fn write(&mut self, bytes: &[u8]) -> Result<(), Self::Error> {
        self.pos += bytes.len();
        Ok(())
    }
}
```

Use it like this:

```rust
let mut serializer = MockSerializer::new();
serializer.serialize_value(&value).expect("failed to serialize");

println!("Serialized data took up {} bytes", serializer.pos());
```

**Comment by mountainfloating** [comment]
Looks Great! Thank you very much!
