### ISSUE TITLE
Serialized format?

### ISSUE THREAD

**Issue by ethindp** [djkoloski/rkyv#87]
Does Rkyv have a serialized format? E.g.: can I use this to read in raw bytes into a data structure like you can in C where you create a `void*` pointer to a data structure in memory and then typecast it to the (handcoded) data structure? Or when I serialize it does it have a particular format it outputs? Apologies if this sounds confusing.

**Comment by djkoloski** [comment]
rkyv has a serialized format, but it's not formally specified since by default it depends on how the compiler lays out types. You can force it to use C-compatible type layouts by enabling the `strict` feature.

> E.g.: can I use this to read in raw bytes into a data structure like you can in C where you create a void* pointer to a data structure in memory and then typecast it to the (handcoded) data structure?

This is exactly what rkyv does, check out [`archived_value`](https://github.com/djkoloski/rkyv/blob/master/rkyv/src/lib.rs#L791). Instead of making each structure by hand, you can derive `Archive` and the macro will generate one for you.

**Comment by ethindp** [comment]
I certainly will check that out! To clarify, though... Assume that I have a struct:
```rust
#[repr(C)]
#[derive(Archive, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
struct MemoryEntry {
pub addr: u64,
pub range: u64,
}
```
And I want to deserialize it from RAM, I can just read in the raw bytes and not have to do any data modification whatsoever? Because if so, I have an embedded project I can throw this at (since the book does indicate it needs testing) and I can significantly reduce my code because the only other crate I know to do this is Zerocopy, and I've exceeded that crates capabilities.
Furthermore, how would I then serialize the (de)serialized form back into raw bytes? Would I need to write a custom serializer for it?

**Comment by djkoloski** [comment]
This is something I would recommend checking out [the book](https://davidkoloski.me/rkyv) for more info on, but here's a quick summary of how rkyv works:

When you derive `Archive` for a type, it generates a new type that is suitable for zero-copy deserialization. You keep the original type as the "in-memory" or "live" representation. So for your example, you'd have `MemoryEntry` and `ArchivedMemoryEntry`. When you serialize your `MemoryEntry`, it converts it to an `ArchivedMemoryEntry` and writes out the bytes for that type. When you want to access your archived type, you can just cast a pointer and get an `ArchivedMemoryEntry`.

For some types, no serialization is necessary because they're only composed of types that also require no serialization. The `MemoryEntry` doesn't require any serialization because it's just two `u64` and those don't require any serialization. These types can be copied directly to the output byte-for-byte and you can do just that by adding `#[archive(copy)]` to your struct. This makes the `Archive` macro use your struct as both the archived and live versions and doesn't generate an `ArchivedMemoryEntry`.

You can't use `#[archive(copy)]` on structs that require serialization. For example, if a struct has a `String` field, you need to serialize the bytes for that string. In that case, you just drop the `#[archive(copy)]` and it will generate an archived version of your type.

**Comment by djkoloski** [comment]
Closing this, if you have any more questions feel free to reopen, file a new issue, or hop in the discord to ask questions.
